package sql

import (
	"strings"
	"testing"
)

func TestColumnTypes_mysqlOmitsDeprecatedZeroFill(t *testing.T) {
	// Given
	typeDefinitions := ColumnTypes(DatabaseInfo{Product: "MySQL"})

	// When
	for _, typeDefinition := range typeDefinitions {
		if typeDefinition.Name == "INT ZEROFILL" || typeDefinition.Name == "INT UNSIGNED ZEROFILL" {
			t.Fatalf("deprecated type = %q, want omitted", typeDefinition.Name)
		}
	}

	// Then
	foundUnsigned := false
	for _, typeDefinition := range typeDefinitions {
		if typeDefinition.Name == "INT UNSIGNED" {
			foundUnsigned = true
		}
	}
	if !foundUnsigned {
		t.Fatal("INT UNSIGNED is missing")
	}
}

func TestColumnTypes_attributeOptionsPerDriverAndType(t *testing.T) {
	tests := []struct {
		product, typeName string
		want              []string
	}{
		{"MySQL", "INT", []string{"AUTO_INCREMENT"}},
		{"MySQL", "BIGINT UNSIGNED", []string{"AUTO_INCREMENT"}},
		{"MySQL", "TEXT", nil},
		{"PostgreSQL", "INTEGER", []string{"GENERATED ALWAYS AS IDENTITY", "GENERATED BY DEFAULT AS IDENTITY"}},
		{"PostgreSQL", "UUID", nil},
		{"SQLite", "INTEGER", nil},
	}
	for _, tt := range tests {
		for _, typeDefinition := range ColumnTypes(DatabaseInfo{Product: tt.product}) {
			if !strings.EqualFold(typeDefinition.Name, tt.typeName) {
				continue
			}
			if len(typeDefinition.Attributes) != len(tt.want) {
				t.Errorf("%s %s attributes = %v, want %v", tt.product, tt.typeName, typeDefinition.Attributes, tt.want)
				continue
			}
			for index := range tt.want {
				if typeDefinition.Attributes[index] != tt.want[index] {
					t.Errorf("%s %s attributes = %v, want %v", tt.product, tt.typeName, typeDefinition.Attributes, tt.want)
				}
			}
		}
	}
}

func TestColumnTypes_everyTypeHasFriendlyLabel(t *testing.T) {
	for _, product := range []string{"MySQL", "PostgreSQL", "SQLite"} {
		for _, typeDefinition := range ColumnTypes(DatabaseInfo{Product: product}) {
			if typeDefinition.Label == "" {
				t.Errorf("%s %s has no picker label", product, typeDefinition.Name)
				continue
			}
			if !strings.HasPrefix(typeDefinition.Label, typeDefinition.Name+" — ") {
				t.Errorf("%s %s label = %q, want %q prefix", product, typeDefinition.Name, typeDefinition.Label, typeDefinition.Name+" — ")
			}
		}
	}
}

func TestColumnTypeDeclaration_buildsParameterizedType(t *testing.T) {
	// Given
	typeDefinition := ColumnType{Name: "DECIMAL", Parameters: []ColumnTypeParameter{{Name: "Precision", Default: "10"}, {Name: "Scale", Default: "2"}}}

	// When
	declaration, err := typeDefinition.Declaration([]string{"12", "2"})

	// Then
	if err != nil {
		t.Fatalf("Declaration() error = %v", err)
	}
	if declaration != "DECIMAL(12,2)" {
		t.Errorf("declaration = %q, want DECIMAL(12,2)", declaration)
	}
}

func TestColumnTypeDeclaration_rejectsScaleAbovePrecision(t *testing.T) {
	// Given
	typeDefinition := ColumnType{Name: "DECIMAL", Parameters: []ColumnTypeParameter{{Name: "Precision", Default: "10"}, {Name: "Scale", Default: "2"}}}

	// When
	_, err := typeDefinition.Declaration([]string{"2", "3"})

	// Then
	if err == nil {
		t.Fatal("Declaration() error = nil, want scale validation error")
	}
}

func TestIsNumericColumnType_recognizes_database_numeric_types(t *testing.T) {
	for typeName, want := range map[string]bool{
		"INTEGER":         true,
		"DECIMAL(10,2)":   true,
		"BIGINT UNSIGNED": true,
		"TEXT":            false,
		"BOOLEAN":         false,
		"":                false,
	} {
		// Given
		// When
		got := IsNumericColumnType(typeName)

		// Then
		if got != want {
			t.Errorf("IsNumericColumnType(%q) = %t, want %t", typeName, got, want)
		}
	}
}
