package sql

import (
	"fmt"
	"strconv"
	"strings"
)

type ColumnTypeParameter struct {
	Name    string
	Default string
}

type ColumnType struct {
	Name       string
	Parameters []ColumnTypeParameter
	Attributes []string
	// Label is the human-friendly picker entry, e.g. "VARCHAR — variable-length
	// string". Empty means the type name is shown as-is.
	Label string
}

func ColumnTypes(info DatabaseInfo) []ColumnType {
	length := ColumnTypeParameter{Name: "Length", Default: "255"}
	decimal := []ColumnTypeParameter{{Name: "Precision", Default: "10"}, {Name: "Scale", Default: "2"}}
	if info.Product == "MySQL" {
		autoIncrement := []string{"AUTO_INCREMENT"}
		return []ColumnType{
			{Name: "TINYINT", Label: "TINYINT — very small integer", Attributes: autoIncrement},
			{Name: "TINYINT UNSIGNED", Label: "TINYINT UNSIGNED — very small non-negative integer", Attributes: autoIncrement},
			{Name: "SMALLINT", Label: "SMALLINT — small integer", Attributes: autoIncrement},
			{Name: "SMALLINT UNSIGNED", Label: "SMALLINT UNSIGNED — small non-negative integer", Attributes: autoIncrement},
			{Name: "MEDIUMINT", Label: "MEDIUMINT — medium integer", Attributes: autoIncrement},
			{Name: "MEDIUMINT UNSIGNED", Label: "MEDIUMINT UNSIGNED — medium non-negative integer", Attributes: autoIncrement},
			{Name: "INT", Label: "INT — standard integer", Attributes: autoIncrement},
			{Name: "INT UNSIGNED", Label: "INT UNSIGNED — standard non-negative integer", Attributes: autoIncrement},
			{Name: "BIGINT", Label: "BIGINT — large integer", Attributes: autoIncrement},
			{Name: "BIGINT UNSIGNED", Label: "BIGINT UNSIGNED — large non-negative integer", Attributes: autoIncrement},
			{Name: "DECIMAL", Label: "DECIMAL — exact decimal (precision, scale)", Parameters: decimal},
			{Name: "NUMERIC", Label: "NUMERIC — exact decimal (precision, scale)", Parameters: decimal},
			{Name: "FLOAT", Label: "FLOAT — floating-point number"},
			{Name: "DOUBLE", Label: "DOUBLE — double-precision floating-point number"},
			{Name: "CHAR", Label: "CHAR — fixed-length string", Parameters: []ColumnTypeParameter{length}},
			{Name: "VARCHAR", Label: "VARCHAR — variable-length string", Parameters: []ColumnTypeParameter{length}},
			{Name: "BINARY", Label: "BINARY — fixed-length binary data", Parameters: []ColumnTypeParameter{length}},
			{Name: "VARBINARY", Label: "VARBINARY — variable-length binary data", Parameters: []ColumnTypeParameter{length}},
			{Name: "TEXT", Label: "TEXT — long text"},
			{Name: "BLOB", Label: "BLOB — binary data"},
			{Name: "DATE", Label: "DATE — calendar date"},
			{Name: "TIME", Label: "TIME — time of day"},
			{Name: "DATETIME", Label: "DATETIME — date and time"},
			{Name: "TIMESTAMP", Label: "TIMESTAMP — date and time, auto-updating"},
			{Name: "BOOLEAN", Label: "BOOLEAN — true or false"},
			{Name: "JSON", Label: "JSON — JSON document"},
		}
	}
	if info.Product == "PostgreSQL" {
		identity := []string{"GENERATED ALWAYS AS IDENTITY", "GENERATED BY DEFAULT AS IDENTITY"}
		return []ColumnType{
			{Name: "SMALLINT", Label: "SMALLINT — small integer", Attributes: identity},
			{Name: "INTEGER", Label: "INTEGER — integer", Attributes: identity},
			{Name: "BIGINT", Label: "BIGINT — large integer", Attributes: identity},
			{Name: "NUMERIC", Label: "NUMERIC — exact decimal (precision, scale)", Parameters: decimal},
			{Name: "DECIMAL", Label: "DECIMAL — exact decimal (precision, scale)", Parameters: decimal},
			{Name: "REAL", Label: "REAL — floating-point number"},
			{Name: "DOUBLE PRECISION", Label: "DOUBLE PRECISION — double-precision floating-point number"},
			{Name: "CHAR", Label: "CHAR — fixed-length string", Parameters: []ColumnTypeParameter{length}},
			{Name: "VARCHAR", Label: "VARCHAR — variable-length string", Parameters: []ColumnTypeParameter{length}},
			{Name: "TEXT", Label: "TEXT — unbounded text"},
			{Name: "BYTEA", Label: "BYTEA — binary data"},
			{Name: "BOOLEAN", Label: "BOOLEAN — true or false"},
			{Name: "DATE", Label: "DATE — calendar date"},
			{Name: "TIME", Label: "TIME — time of day"},
			{Name: "TIMESTAMP", Label: "TIMESTAMP — date and time"},
			{Name: "TIMESTAMPTZ", Label: "TIMESTAMPTZ — date and time with time zone"},
			{Name: "UUID", Label: "UUID — unique identifier"},
			{Name: "JSONB", Label: "JSONB — binary JSON document"},
		}
	}
	return []ColumnType{
		{Name: "INTEGER", Label: "INTEGER — whole number"},
		{Name: "REAL", Label: "REAL — floating-point number"},
		{Name: "TEXT", Label: "TEXT — string"},
		{Name: "BLOB", Label: "BLOB — binary data"},
		{Name: "NUMERIC", Label: "NUMERIC — number or string", Parameters: decimal},
		{Name: "DECIMAL", Label: "DECIMAL — exact decimal (precision, scale)", Parameters: decimal},
		{Name: "CHAR", Label: "CHAR — fixed-length string", Parameters: []ColumnTypeParameter{length}},
		{Name: "VARCHAR", Label: "VARCHAR — variable-length string", Parameters: []ColumnTypeParameter{length}},
		{Name: "DATE", Label: "DATE — calendar date"},
		{Name: "DATETIME", Label: "DATETIME — date and time"},
		{Name: "BOOLEAN", Label: "BOOLEAN — true or false"},
	}
}

func (t ColumnType) Declaration(values []string) (string, error) {
	if len(values) != len(t.Parameters) {
		return "", fmt.Errorf("%s requires %d parameters", t.Name, len(t.Parameters))
	}
	if len(values) == 0 {
		return t.Name, nil
	}
	parsed := make([]int, len(values))
	for index, value := range values {
		number, err := strconv.Atoi(strings.TrimSpace(value))
		if err != nil || number < 0 || (t.Parameters[index].Name != "Scale" && number == 0) {
			return "", fmt.Errorf("%s must be a valid %s", t.Parameters[index].Name, positiveName(t.Parameters[index].Name))
		}
		parsed[index] = number
	}
	if len(parsed) == 2 && t.Parameters[0].Name == "Precision" && parsed[1] > parsed[0] {
		return "", fmt.Errorf("scale cannot exceed precision")
	}
	return t.Name + "(" + strings.Join(values, ",") + ")", nil
}

func MatchColumnType(types []ColumnType, declaration string) (int, []string, bool) {
	declaration = strings.TrimSpace(declaration)
	for index, typeDefinition := range types {
		if len(typeDefinition.Parameters) == 0 && strings.EqualFold(typeDefinition.Name, declaration) {
			return index, nil, true
		}
		if len(typeDefinition.Parameters) == 0 || len(declaration) <= len(typeDefinition.Name) || !strings.EqualFold(declaration[:len(typeDefinition.Name)], typeDefinition.Name) {
			continue
		}
		remainder := strings.TrimSpace(declaration[len(typeDefinition.Name):])
		if len(remainder) < 3 || remainder[0] != '(' || remainder[len(remainder)-1] != ')' {
			continue
		}
		values := strings.Split(remainder[1:len(remainder)-1], ",")
		if len(values) != len(typeDefinition.Parameters) {
			continue
		}
		if _, err := typeDefinition.Declaration(values); err == nil {
			return index, values, true
		}
	}
	return 0, nil, false
}

func IsNumericColumnType(typeName string) bool {
	typeName = strings.ToUpper(strings.TrimSpace(typeName))
	typeName, _, _ = strings.Cut(typeName, "(")
	typeName, _, _ = strings.Cut(typeName, " ")
	switch typeName {
	case "TINYINT", "SMALLINT", "MEDIUMINT", "INT", "INTEGER", "BIGINT", "LONG",
		"DECIMAL", "NUMERIC", "FLOAT", "DOUBLE", "REAL":
		return true
	default:
		return false
	}
}

func positiveName(name string) string {
	if name == "Scale" {
		return "non-negative " + strings.ToLower(name)
	}
	return "positive " + strings.ToLower(name)
}
